version: "3.4"
services:
  crossover-eval:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      echo start
      && python3 main.py -mp 0.05 -cp 0.3 -s 0 -t test  
      "
    volumes:
      - ./results:/app/results
